#!/usr/bin/env expect
set timeout 360

spawn vue init . demo

# This happens because of
# https://github.com/vuejs/vue-cli/issues/291
expect "Project name" { send "\n" }
expect "Project description" { send "\n" }
expect "Author" { send "\n" }
expect "Use i18n?" { send "n\n" }
expect "With ansible?" { send "n\n" }
expect "With travis?" { send "\n" }
expect "vue-cli · Generated" { send "\n" }
